#!/bin/sh
# This script runs tools to make the source code more pre-ANSI-C compliant

PREANSI="preansifunc.sed"
PREANSI_FILTER="paf_nc.sed"
sed 's/^#.*//' < $PREANSI > $PREANSI_FILTER

for src_file in "$@"; do
    sed -f $PREANSI_FILTER < $src_file
done

rm $PREANSI_FILTER
